{"uuid":"663c1287-f24a-4c03-ba16-f2e6480dd766","name":"Вход с неверным логином","historyId":"075cfe38372b43bf771f6b49b7e99c80:fda9d2b14d7d6a303c5a1b99663b70ee","status":"failed","statusDetails":{"message":"expect(received).rejects.toThrow(expected)\n\nExpected substring: \"Пользователь с логином new_login не найден\"\nReceived message:   \"Неверный логин или пароль\"\n\n      38 |         const msg = `Пользователь с логином ${login} не найден`;\n      39 |         logger.error(msg);\n    > 40 |         throw new CredentialsError();\n         |               ^\n      41 |     }\n      42 |\n      43 |     async create(login: string, password: string, name: string, role: number): Promise<number> {\n\n      at PersonRepository.get (src/Repository/Implementations/PersonRepository.ts:40:15)","trace":"Error: expect(received).rejects.toThrow(expected)\n\nExpected substring: \"Пользователь с логином new_login не найден\"\nReceived message:   \"Неверный логин или пароль\"\n\n      38 |         const msg = `Пользователь с логином ${login} не найден`;\n      39 |         logger.error(msg);\n    > 40 |         throw new CredentialsError();\n         |               ^\n      41 |     }\n      42 |\n      43 |     async create(login: string, password: string, name: string, role: number): Promise<number> {\n\n      at PersonRepository.get (src/Repository/Implementations/PersonRepository.ts:40:15)\n    at Object.toThrow (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\expect\\build\\index.js:2155:20)\n    at C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\src\\__tests__\\unit-tests\\authperson.test.ts:156:49\n    at body (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\facade.ts:113:48)\n    at body (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:175:28)\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:12:79)\n    at asyncGeneratorStep (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:12:79)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","actual":"undefined","expected":"undefined"},"stage":"finished","steps":[{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1760967880501,"name":"Подготовка тестовых данных","stop":1760967880502},{"status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1760967880502,"name":"Выполнение команды входа","stop":1760967880502},{"status":"failed","statusDetails":{"message":"expect(received).rejects.toThrow(expected)\n\nExpected substring: \"Пользователь с логином new_login не найден\"\nReceived message:   \"Неверный логин или пароль\"\n\n      38 |         const msg = `Пользователь с логином ${login} не найден`;\n      39 |         logger.error(msg);\n    > 40 |         throw new CredentialsError();\n         |               ^\n      41 |     }\n      42 |\n      43 |     async create(login: string, password: string, name: string, role: number): Promise<number> {\n\n      at PersonRepository.get (src/Repository/Implementations/PersonRepository.ts:40:15)","trace":"Error: expect(received).rejects.toThrow(expected)\n\nExpected substring: \"Пользователь с логином new_login не найден\"\nReceived message:   \"Неверный логин или пароль\"\n\n      38 |         const msg = `Пользователь с логином ${login} не найден`;\n      39 |         logger.error(msg);\n    > 40 |         throw new CredentialsError();\n         |               ^\n      41 |     }\n      42 |\n      43 |     async create(login: string, password: string, name: string, role: number): Promise<number> {\n\n      at PersonRepository.get (src/Repository/Implementations/PersonRepository.ts:40:15)\n    at Object.toThrow (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\expect\\build\\index.js:2155:20)\n    at C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\src\\__tests__\\unit-tests\\authperson.test.ts:156:49\n    at body (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\facade.ts:113:48)\n    at body (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:175:28)\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:12:79)\n    at asyncGeneratorStep (C:\\Users\\User\\Desktop\\uni\\testanddebug\\Server\\node_modules\\allure-js-commons\\src\\sdk\\runtime\\MessageTestRuntime.ts:12:79)\n    at processTicksAndRejections (node:internal/process/task_queues:105:5)","actual":"undefined","expected":"undefined"},"stage":"finished","steps":[],"attachments":[],"parameters":[],"start":1760967880502,"name":"Проверка ошибки неверного логина","stop":1760967880518}],"attachments":[],"parameters":[{"name":"login","value":"new_login"},{"name":"password","value":"password"},{"name":"Текст ошибки","value":"Пользователь с логином new_login не найден"}],"labels":[{"name":"language","value":"javascript"},{"name":"framework","value":"jest"},{"name":"package","value":"src.__tests__.unit-tests.authperson.test.ts"},{"name":"host","value":"LAPTOP-7FFNEF67"},{"name":"thread","value":"1"},{"name":"parentSuite","value":"Вход и регистрация пользователя"}],"links":[],"start":1760967880500,"fullName":"src/__tests__/unit-tests/authperson.test.ts#Вход и регистрация пользователя Вход с неверным логином","titlePath":["src","__tests__","unit-tests","authperson.test.ts","Вход и регистрация пользователя"],"testCaseId":"075cfe38372b43bf771f6b49b7e99c80","stop":1760967880519}